apimServiceName: apim-radshow-stg01-cin
namedValues:
  - name: backend-url-functions-primary
    properties:
      displayName: backend-url-functions-primary
      value: https://func-radshow-stg01-cin.azurewebsites.net/api
  - name: backend-url-functions-secondary
    properties:
      displayName: backend-url-functions-secondary
      value: https://func-radshow-stg01-sin.azurewebsites.net/api
  - name: backend-url-aca-primary
    properties:
      displayName: backend-url-aca-primary
      value: https://ca-products-radshow-stg01-cin.happysea-a428f96b.centralindia.azurecontainerapps.io
  - name: backend-url-aca-secondary
    properties:
      displayName: backend-url-aca-secondary
      value: https://ca-products-radshow-stg01-sin.mangosea-b9cd4f1e.southindia.azurecontainerapps.io
  - name: tenant-id
    properties:
      displayName: tenant-id
      value: 6021aa37-5a44-450a-8854-f08245985be2
  - name: api-audience
    properties:
      displayName: api-audience
      value: api://radshow-stg01
  - name: secondary-region
    properties:
      displayName: secondary-region
      value: South India
backends:
  - name: functions-primary
    properties:
      url: https://func-radshow-stg01-cin.azurewebsites.net/api
  - name: functions-secondary
    properties:
      url: https://func-radshow-stg01-sin.azurewebsites.net/api
  - name: aca-primary
    properties:
      url: https://ca-products-radshow-stg01-cin.happysea-a428f96b.centralindia.azurecontainerapps.io
  - name: aca-secondary
    properties:
      url: https://ca-products-radshow-stg01-sin.mangosea-b9cd4f1e.southindia.azurecontainerapps.io
apis:
  - name: radshow-api
    properties:
      serviceUrl: https://func-radshow-stg01-cin.azurewebsites.net/api
  - name: radshow-product-api
    properties:
      serviceUrl: https://ca-products-radshow-stg01-cin.happysea-a428f96b.centralindia.azurecontainerapps.io/products
