apimServiceName: apim-radshow-dev01
namedValues:
  - name: backend-url-functions-primary
    properties:
      displayName: backend-url-functions-primary
      value: https://func-radshow-dev01.azurewebsites.net/api
  - name: backend-url-functions-secondary
    properties:
      displayName: backend-url-functions-secondary
      value: https://func-radshow-dev01.azurewebsites.net/api
  - name: backend-url-aca-primary
    properties:
      displayName: backend-url-aca-primary
      value: https://app-radshow-dev01.azurewebsites.net
  - name: backend-url-aca-secondary
    properties:
      displayName: backend-url-aca-secondary
      value: https://app-radshow-dev01.azurewebsites.net
  - name: tenant-id
    properties:
      displayName: tenant-id
      value: 6021aa37-5a44-450a-8854-f08245985be2
  - name: api-audience
    properties:
      displayName: api-audience
      value: api://radshow-dev01
backends:
  - name: functions-primary
    properties:
      url: https://func-radshow-dev01.azurewebsites.net/api
  - name: functions-secondary
    properties:
      url: https://func-radshow-dev01.azurewebsites.net/api
  - name: aca-primary
    properties:
      url: https://app-radshow-dev01.azurewebsites.net
  - name: aca-secondary
    properties:
      url: https://app-radshow-dev01.azurewebsites.net
apis:
  - name: radshow-api
    properties:
      serviceUrl: https://func-radshow-dev01.azurewebsites.net/api
